#cloud-config
repo_update: true
repo_upgrade: all

packages:
  - docker.io
  - git

# create the docker group
groups:
  - docker

# Add default auto created user to docker group
system_info:
  default_user:
    groups: [docker]

runcmd:
 - sleep 10
 - sudo systemctl enable docker 
 - sudo systemctl start docker
 - git clone https://github.com/BradStone-dev/go-http-server
 - cd go-http-server
 - sudo docker build -t go-http-app .
 - sudo docker run -d -p 8080:8080/tcp --restart=always --env MY_SPECIAL_DEBUG_VARIABLE=${debug_variable} --env MY_SPECIAL_VERSION=`git describe --tags --abbrev=0` go-http-app
